# Site settings
title: Ganni's
email: ganni4@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ganni4
github_username:  ganni
disqus_shortname: gannigithubio
google_analytics: UA-3158208-9
chat: TRUE

# Build settings
markdown: kramdown
highlighter: rouge

port: 3000
future: TRUE
permalink: /:year/:month/:day/:title.html
